version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: test_postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    networks:
      - test-network

networks:
  test-network:
    driver: bridge